# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AdBrixSampleProject_ios' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AdBrixSampleProject_ios

  pod 'AdBrixRemastered'


end
